<table>
    <tr>
        <th>receivingno</th>
        <th>invoiceno</th>
        <th>item</th>
        <th>Qty</th>
        <th>package_category</th>
        <th>package_qty</th>
        <th>LotNo</th>
        <th>supplier</th>
        <th>not_required_iqc</th>
        <th>received_date</th>
    </tr>
</table>